### PR TITLE
UI Update. Fixes #81

### LINKED ISSUE #81: P3: Clean up feature detail UI
Current design: 

image

<hr><hr>

Proposed design:

(It's ugly but it's the general idea.)

image

<hr><hr>

Bullet points: 

* see all information without having to hover (better for mobile)
* More context for all information
* intent threads added
* visualization of browser support added

For mobile, these two columns collapse to one:
<hr><hr>

### PR DESCRIPTION
**Pull request by ebidel**
R: @jeffposnick 

UI refresh to make things more legible and easier to grok. We've become very information dense over the years.

screen shot 2015-12-16 at 2 29 57 pm

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
Quick feedback: 

- Custom grey tooltips in Chrome 49.0.2587.3 are misplaced

screenshot 2015-12-17 at 9 54 31 am - display 1

- There is a missing comma between links and samples

screenshot 2015-12-17 at 10 02 05 am

**Comment by jeffposnick** [comment]
Looks good in general! Not sure if the tooltip positioning is a big problem, though I agree the samples/links list looks a bit weird as it's currently formatted.

My main feedback is about the W3C logo next to the "standards" link. I know that some standards might come out of different committees. Will using that logo ruffle some feathers?

**Comment by ebidel** [comment]
PTAL. The placement of the tooltips I'm not worried about. Added the , and removed the w3c logo just to be safe. Also fixed a few scrolling bugs.

**Comment by jeffposnick** [comment]
:+1:

**Pull request merged**
