### PR TITLE
Use identical text for equivalent stages.

### PR DESCRIPTION
**Pull request by jpmedley**
There will probably be some discussion.

### CODE REVIEW

**Comment by jstenback** [comment]
I too would like to hear what @cwilso thinks about this change but from my perspective this reduces the number of differences in wording between intent stages and implementation stages, which feels like a good thing.

**Review by Vladisvob — APPROVED** [review]
#2279

**Review by Vladisvob — APPROVED** [review]
Duplicate of #

**Comment by jrobbins** [comment]
@cwilso ping on these wording changes

**Review by cwilso — APPROVED** [review]
LGTM

**Comment by jrobbins** [comment]
This PR cannot merge any more, but I will redo it as a new PR.

**Pull request closed without merging**
