### PR TITLE
run npm upgrade

### PR DESCRIPTION
**Pull request by jrobbins**
This is the result of running `rpm upgrade`.  It changes a bunch of JS package versions, which gives us some bug fixes but may also have introduced new bugs.

### CODE REVIEW

**Comment by jcscottiii** [comment]
Could rebase this change on the latest main?

I see this [commit](https://github.com/GoogleChrome/chromium-dashboard/commit/7e58b19848e14660327908cfa48fc2a2e57d867c) that should solve a few of the lint issues.

**Comment by jrobbins** [comment]
> Could rebase this change on the latest main?
> 
> I see this [commit](https://github.com/GoogleChrome/chromium-dashboard/commit/7e58b19848e14660327908cfa48fc2a2e57d867c) that should solve a few of the lint issues.

There are still some lint errors and warnings.  I'll send a separate PR to solve more of them and then mark this one non-draft at that time.

**Comment by jcscottiii** [comment]
Currently, this PR has no changes

image


https://github.com/GoogleChrome/chromium-dashboard/compare/20230708-run-npm-upgrade

Did another PR bring in these changes already?

**Comment by jrobbins** [comment]
Gah.  I must have done an `npm clean-setup` while working on `main` or another branch.
I'll redo.

**Comment by jrobbins** [comment]
Actually, I remember now.  I had a merge conflict and I resolved it by reverting the change and then I was going to run `npm upgrade` again but I missed that step.

**Review by jcscottiii — APPROVED** [review]

**Pull request merged**
