### PR TITLE
Add "Browser intervention" to impl status. Fixes #407

### LINKED ISSUE #407: Add intervention category
It would be nice to have a category for interventions. Folks are already adding them to the list (https://www.chromestatus.com/features#intervention), but a proper category/label for sorting/filtering would be even better.

screen shot 2016-09-06 at 2 39 59 pm

### PR DESCRIPTION
**Pull request by ebidel**
R: @jeffposnick @RByers @mdittmer @drufball 

Gavel!

screen shot 2016-09-06 at 5 18 52 pm

### CODE REVIEW

**Comment by jeffposnick** [comment]
What do you think about a stop sign or an open hand (like ✋) instead of the gavel? To get across the fact that the intention is to stop certain behavior.

**Comment by ebidel** [comment]
I thought about a stop sign but it might be too close to "removed". Hand might better.

**Comment by beaufortfrancois** [comment]
Here are some suggestions:
https://design.google.com/icons/#ic_pan_tool
https://design.google.com/icons/#ic_block
https://design.google.com/icons/#ic_remove_circle

**Comment by ebidel** [comment]
@paulewis likes the gavel

**Comment by ebidel** [comment]
✋ is good:

screen shot 2016-09-07 at 9 34 34 am

**Comment by ebidel** [comment]
Going to merge!

**Pull request merged**
