### PR TITLE
Adding polymer summit video

### PR DESCRIPTION
**Pull request by ebidel**
R: @beaufortfrancois @jeffposnick @mdittmer @RByers 

-Also makes footer span entire page on desktop

screen shot 2016-10-19 at 5 39 14 pm

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
When window innerWidth is 653px, footer get in this weird state (see below).
Notice how the "Chrome Platform Status" is also merged into the "Chrome logo" at the top.

screenshot 2016-10-20 at 9 26 22 am

**Comment by ebidel** [comment]
Yep, the inbetween breakpoint weirdness isn't new. I've noticed that before and we should fix it, but this PR is unrelated :)

**Comment by ebidel** [comment]
Done

**Comment by beaufortfrancois** [comment]
LGTM

**Pull request merged**
