### PR TITLE
Eliminate list bullets on Firefox in metrics nav

### LINKED ISSUE #306: Stack rank and timeline features show a list bullet in Firefox
https://www.chromestatus.com/metrics/css/animated

The buttons to switch between stack rank and timeline have a list bullet shown:

image

### PR DESCRIPTION
**Pull request by RByers**
Fixes #306

### CODE REVIEW

**Comment by RByers** [comment]
@NavidZ PTAL

**Comment by NavidZ** [comment]
lgtm

**Comment by RByers** [comment]
Thanks, @ebidel PTAL

**Comment by ebidel** [comment]
Lgtm

**Pull request merged**
