### PR TITLE
Responsive Scroll for narrow viewports

### PR DESCRIPTION
**Pull request by shivamag00**
Review Requested:- @jrobbins 

In this PR. 

- Added support for dynamically setting the number of cards to be displayed at once according to the viewport size.
- In narrow view ports, the UI will be same as that of the larger viewports. Only one milestone will be displayed at once.

### CODE REVIEW

**Comment by shivamag00** [comment]
This is how it looks now


https://user-images.githubusercontent.com/44562091/128510684-fa86aa62-8a81-4830-954b-5592b65c5f39.mp4

**Review by jrobbins — APPROVED** [review]

**Comment by jrobbins** [comment]
There are a few merge conflicts.  I will merge after you resolve the conflicts.

**Comment by saan5** [comment]
agreed

**Comment by saan5** [comment]
agreed

**Comment by shivamag00** [comment]
> There are a few merge conflicts. I will merge after you resolve the conflicts.

Oops... I forgot to rebase. Thank you letting me know. I have now rebased this branch. All the merge conflicts are resolved.

**Comment by shivamag00** [comment]
This should close #1418

**Pull request merged**
