### PR TITLE
Replaced Left Hand Navigation with a dropdown menu

### LINKED ISSUE #1240: Milestone page list without scrollable sidebar
**Is your feature request related to a problem? Please describe.**
While opening milestone pages on chromestatus.com, if you open web page of milestones below 50 or 60, then you have to again scroll to the top of the page. Sometimes, it is annoying, as you are continuously opening multiple milestone pages and again and again scroll to the top to see features list.

**Describe the solution you'd like**
If we just put the milestone pages in a scrollable sidebar, then this problem will resolve, and web page will also look more better.

**Additional context**
https://user-images.githubusercontent.com/74249716/112718842-6e26fa00-8f17-11eb-988e-56f37a02f599.mp4

### PR DESCRIPTION
**Pull request by shivamag00**
This PR should close #1240. 
Review Requested: @jrobbins 

We will have to use JS to add the strings `canary` `dev` `beta` `stable` and others instead of CSS as `content` property will not work with option tag. This is still left to be done. 

In this PR, 

- the left-hand navigation is replaced by a drop-down menu
- all chromium statuses which were not directly accessible by the left hand navigation, have also been added to the drop-down list. This was requested in #1113 

The following image illustrates how left hand navigation now looks:-

The first option is disabled because it is used as a placeholder.

### CODE REVIEW

**Comment by shivamag00** [comment]
I am using JS (ternary operator) to display the strings `'canary'` `'dev'` `'beta'` `'stable'` after version numbers based on the `class` of the '<select>' tag and value of the loop counter. It now looks like the following:-



I will now add a option `All` in the dropdown which will replace the `Select Chrome Version` option. This `All` option will display the all the versions in same order as it is displayed when the page loads up for the first time. I will also try to link the filter input field with the dropdown such that clicking on `X` should select `All` from the dropdown.

**Comment by jrobbins** [comment]
This is promising.  I would like to eventually replace those side links with a set of filtering widgets for a few different fields of the Feature entries.  This seems like a good step in that direction.  

The label "Chrome versions" is not quite right because there is a mix of implementation status values and version numbers.  The existing UI also mixed those concepts, but putting it in a menu seems to make the problem more noticeable.  Tomorrow, I'll test out this change and try to come up with a better label.

**Comment by shivamag00** [comment]
UPDATE: Clicking on `X` in the Filter Search Box will now change the selected dropdown option in `Chrome Versions` to `Select Chrome Version`. 

Also, I now think that adding an `All` option to the list will not make much sense as the filter can be cleared using the `X` option. Also, when we separate out the chrome versions and statuses (eventually), the field `All` will not make sense.

**Comment by shivamag00** [comment]
SUGGESTION: I have changed the label to `Filter By` and the placeholder for Dropdown to `Select Chrome Version/Status`. This is how it looks now:-

Screenshot 2021-05-21 202520

**Review by jrobbins — APPROVED** [review]
Well done.  Thanks very much.

**Comment by jrobbins** [comment]
As a follow-up, you might get this filter menu to show on mobile (with narrow viewports).  The old links simply disappeared.  With the filter widgets approach, the widgets could be shown above or below the search box on small screens.  

Don't worry about making similar changes to the /samples page because I am planning on removing that page in the future.

**Comment by shivamag00** [comment]
@jrobbins, #1334 contains the changes to display the filter menu on narrow view ports.

**Pull request merged**
