### PR TITLE
Fix "stats" button top alignment

### PR DESCRIPTION
**Pull request by beaufortfrancois**
FIX: #485

### CODE REVIEW

**Comment by ebidel** [comment]
Not sure this is the right fix. Here's what I get on desktop:

screen shot 2017-08-28 at 9 52 11 am

It also kills the crisp border on the nav buttons.

**Comment by beaufortfrancois** [comment]
Chrome OS looks nice to me. See below
screenshot 2017-08-28 at 9 04 26 pm

Which platform do you see this weird state?

**Comment by ebidel** [comment]
mac

**Comment by beaufortfrancois** [comment]
Here's what I get on Chrome for Mac without this fix. I've used "red" color to show the misalignment:

500%
screen shot 2017-08-29 at 11 57 56 am

400%
screen shot 2017-08-29 at 11 58 04 am

300%
screen shot 2017-08-29 at 11 58 12 am

200% 
screen shot 2017-08-29 at 11 58 23 am

150%
screen shot 2017-08-29 at 11 58 31 am

**Comment by jrobbins** [comment]
This PR is obsolete.  We redid the visual appearance of the site in 2020.

**Pull request closed without merging**
