### PR TITLE
Migrate ApprovalConfig entities to Gate entities

### PR DESCRIPTION
**Pull request by DanielRyanSmith**
Part of the schema migration work.

This script writes all existing ApprovalConfig to new Gate entities.

### CODE REVIEW

**Comment by jrobbins** [comment]
Let's hold on to this PR.  We might not need it because there are actually zero ApprovalConfig entities in our prod datastore.

Maybe instead, we could write the application code to:
1. Create Gates lazily only when one of the Gate fields is updated.  The most common update would be setting a Vote that changes a Gate state.   
2. When displaying Gates: load the ones that exist, but display default data for any defined in internals/processes.py that don't have an entity.

I'll take a hack at a PR to backfill Gates based on existing Approvals (or Votes).

**Review by Vladisvob — CHANGES_REQUESTED** [review]
#2280

**Review by Vladisvob — CHANGES_REQUESTED** [review]
Duplicate of #

**Review by Vladisvob — APPROVED** [review]
#2284

**Review by Vladisvob — APPROVED** [review]
#2285 #2283

**Review by Vladisvob — COMMENTED** [review]
#2283

**Comment by Vladisvob** [comment]
> Part of the schema migration work.
> 
> This script writes all existing ApprovalConfig to new Gate entities.

**Comment by Vladisvob** [comment]
> Let's hold on to this PR. We might not need it because there are actually zero ApprovalConfig entities in our prod datastore.
> 
> Maybe instead, we could write the application code to:
> 
> 1. Create Gates lazily only when one of the Gate fields is updated.  The most common update would be setting a Vote that changes a Gate state.
> 2. When displaying Gates: load the ones that exist, but display default data for any defined in internals/processes.py that don't have an entity.
> 
> I'll take a hack at a PR to backfill Gates based on existing Approvals (or Votes).

**Review by Vladisvob — APPROVED** [review]

**Comment by Vladisvob** [comment]
#2283

**Comment by DanielRyanSmith** [comment]
Because no ApprovalConfig entities currently exist in production, this migration script should not be necessary. Instead, the Stage entity creation script will be upgraded to create gates for each stage that requires intent approval. Closing this.

**Pull request closed without merging**
