### PR TITLE
fix incorrect email notification

### PR DESCRIPTION
**Pull request by kshitjj**
Issue: #3393

Description: Incorrect email used when creating an update feature email

The issue arises from the use of fe.updater_email which results in the owner's email being used. This happens because fe.updater_email corresponds to the owner's email, as the owner is considered the updater when they create the feature.

In the code snippet, updater_email is not passed as a parameter, causing it to default to fe.updater_email.
https://github.com/GoogleChrome/chromium-dashboard/blob/a09e8cb0a04bea37a68e635ff91e68b83fc85c37/internals/notifier.py#L94-L96

The issue was resolved by passing the correct email obtained while creating the `Changes:` part of the email as a parameter. This ensures that the appropriate email is used in the update feature email.

https://github.com/GoogleChrome/chromium-dashboard/blob/a09e8cb0a04bea37a68e635ff91e68b83fc85c37/internals/notifier_helpers.py#L141-L145

### CODE REVIEW

**Review by jrobbins — APPROVED** [review]

**Review by jrobbins — CHANGES_REQUESTED** [review]
Actually, I think you have changed the parameters for a different task than the one that you are giving the new parameters to.

**Comment by kshitjj** [comment]
I could be completely wrong here,  but I think the parameter is given to the right task `notify_subscribers_of_vote_changes()` enqueue a task to `/tasks/email-subscribers`

https://github.com/GoogleChrome/chromium-dashboard/blob/cbcd94ef0c8afa6039bece37e787d662ebd34032/internals/notifier_helpers.py#L155

which is then routed to the notifier.FeatureChangeHandler in main.py
https://github.com/GoogleChrome/chromium-dashboard/blob/cbcd94ef0c8afa6039bece37e787d662ebd34032/main.py#L264

Then FeatureChangeHandler receives the parameter
https://github.com/GoogleChrome/chromium-dashboard/blob/e0ad40211e9959cad5ccab7c9a1bc9b1804c209a/internals/notifier.py#L404-L415

**Comment by kshitjj** [comment]
It seems like I pasted it in the wrong function while switching branches :sweat_smile:

**Comment by jrobbins** [comment]
I still don't think that you quite got it right.  The existing code is probably more complicated than it should be, so it is challenging to make a change here.  Inspired by your change, I went ahead and worked through a fix that I think is right in #3675.  If that PR gets merged, we can close this one.  Thanks for bringing my attention to this bug.

**Comment by kshitjj** [comment]
I guess I accidentally helped you. 😅

can you refer to me documentation that will help understand me the workflow?

**Comment by jrobbins** [comment]
There's no documentation for that code.   You can see which functions work together by their names, and by the URI of the task generated in notification_helpers.py vs. the class that handles that task specified in main.py.

Thanks again.

**Pull request closed without merging**
