### PR TITLE
Add 'On hold' to Chromium statuses.

### PR DESCRIPTION
**Pull request by jpmedley**

### CODE REVIEW

**Comment by jpmedley** [comment]
@jrobbins Can you look at this today. I actually need to set this on a feature.

**Comment by jrobbins** [comment]
Sorry to be late reviewing that change.  I went ahead and landed it and I can deploy later today.

**Comment by jpmedley** [comment]
Did you deploy this? I don't see it in the interface even after a hard
reload.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by jpmedley** [comment]
Thank you.
Joe Medley | Technical Writer, Chrome DevRel | jmedley@google.com |
 816-678-7195
*If an API's not documented it doesn't exist.*

**Comment by jrobbins** [comment]
I hit problems with 'npm' on my cloudtop instance that day. That is resolved now.  I will wait until your other CL lands and then deploy today.

**Comment by jrobbins** [comment]
This is live now.

**Pull request merged**
