### PR TITLE
Scroll Behaviour on upcoming page

### PR DESCRIPTION
**Pull request by shivamag00**
Review Requested:- @jrobbins 

In this PR, 

- added scroll behaviour in the new upcoming page

### CODE REVIEW

**Comment by shivamag00** [comment]
This is how the UI looks:- 

https://user-images.githubusercontent.com/44562091/128244462-af40bf8a-aaf0-4b10-8df8-f219e77fde95.mp4

**Comment by shivamag00** [comment]
@jrobbins, the following is still left to be done:-

1. Semi-infinite scroll: Currently, it shows information of four milestones. To access the fourth milestone, one will have to click on the next button. The functionality to access more versions in the future needs to be added. **I will add this support in the next PR.**
2. Greyscale Chrome Logo for milestones later than dev.
3. Positioning of arrows to the left and right of the milestone card container.
4. Making the page responsive for narrow view ports.

**Comment by shivamag00** [comment]
@jrobbins,
 I have added the following:-

1. Greyscale Chrome Logo for milestones later than dev.
2. Making the page responsive for narrow view ports.
3. Code optimizations

**Comment by shivamag00** [comment]
This is how the page now looks:-

Capture

**Review by jrobbins — APPROVED** [review]
This all looks good.

**Pull request merged**
