### PR TITLE
Use datalist instead of select

### PR DESCRIPTION
**Pull request by shubhammittal588**
This should resolve issue #1342 .

In this PR:
1. Changed select tag with input tag and added attributes type="search" list=“features" .
2. Used datalist tag with attribute id=“features”.
3. Changed the attribute to be the name of the UseCounter in option tag.

### CODE REVIEW

**Comment by jrobbins** [comment]
I think you might be missing a commit.  The diffs for this PR do not match what you wrote in the PR description.

**Comment by shubhammittal588** [comment]
I have committed the diffs, this is the screenshot of the commit I made.
Screenshot 2021-07-10 at 1 08 48 PM

**Comment by jrobbins** [comment]
I think this could be made to work, but it is not working right now there is a UX problem also.

The current code is causing the bucket name to be placed in the URL of the API request.  Instead, it needs to be the bucket ID number.  Or, the API handler needs to be modified to accept either names or IDs.

When the user clicks on the widget, nothing happens initially.  So, it is not so clear what the purpose of this widget is or what options are available.  If the user types "a" they will see options that contain the letter "a", but there does not seem to be a good way to see the entire list.  The prompt "Select a property" is not visible, so there is no indication that the user should do anything with this widget.

**Comment by jrobbins** [comment]
I'm going to close this to clear up our list of pending PRs.  But, I will keep this code in mind when I eventually get around to redesigning this page.

**Pull request closed without merging**
