### PR TITLE
Added basic canonical samples page

### PR DESCRIPTION
**Pull request by beaufortfrancois**
DO NOT MERGE

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
Following https://github.com/GoogleChrome/samples/issues/221#issuecomment-147722868, @ebidel what do you think of something simple as this?

screenshot 2015-10-13 at 11 35 38 am

screenshot 2015-10-13 at 11 36 33 am

**Comment by ebidel** [comment]
I'm not sure a landing page for samples is needed. It doesn't offer much
more than the list card and it could be confusing with the feature landing
page.

**Comment by beaufortfrancois** [comment]
I guess I'll stick to https://www.chromestatus.com/samples#bluetooth then. Thanks!

**Comment by ebidel** [comment]
Going to close this.

**Pull request closed without merging**
