### PR TITLE
Validate Chromium inputs for OT creation (UI)

### PR DESCRIPTION
**Pull request by DanielRyanSmith**
This PR adds a number of checks when the user attempts to submit an OT Creation request that validates the input is in the correct format in accordance with the Chromium code. This PR does not include these checks server-side, which will come in a later PR.

Checks each of these params are set up in Chromium:
- Webfeature UseCounter
- Chromium trial name
- Third-party support setting
- Critical trial grace period setting

This is checked by obtaining the Chromium file contents and ensuring the files contain the given information as expected.

Some of the definitions of the form fields have been updated to include links to the files that require the data be added.

Note: These checks are handled on a submission attempt, so they are not handled through the semantic checks process, which is processed after each input change.

Screenshot 2024-04-10 at 11 59 16 AM

https://github.com/GoogleChrome/chromium-dashboard/assets/56164590/0a7ee267-79e3-4ae4-bfed-540030fa1182

### CODE REVIEW

**Comment by jrobbins** [comment]
Is this PR ready for review?

**Comment by DanielRyanSmith** [comment]
@jrobbins It is now, yes 🙂

**Review by jrobbins — APPROVED** [review]
LGTM.

How long does it take to download the files after the user hits "submit"?

**Comment by DanielRyanSmith** [comment]
> How long does it take to download the files after the user hits "submit"?

The check process has felt very fast testing locally (<1 second). In the short video above, the file contents are requested and checks are completed each time the submit button is pressed, so that should be a relatively accurate reflection.

I'll need to make a change to the logic based on today's discussion of critical trials before merging.

**Pull request merged**
