### PR TITLE
Migrate Feature entities to FeatureEntry entities

### PR DESCRIPTION
**Pull request by DanielRyanSmith**
Part of the schema migration work.

This script writes all existing features to new FeatureEntry entities. *Note*: This script only copies over fields on the Feature kind that should exist on any FeatureEntry entities. Additional work will be necessary to move some Feature fields that are not part of the schema of different kinds.

### CODE REVIEW

**Comment by DanielRyanSmith** [comment]
@jrobbins This might need clarification and refactoring, as I only copied over known fields and their new formats or named. Let me know if anything need to also be migrated at the same time, or I've missed something here. 🙂

**Comment by DanielRyanSmith** [comment]
@jrobbins, I believe this is ready for review now - sorry for the hasty review request 😅

**Comment by jrobbins** [comment]
I assume you are are going to simplify this after landing your other PR.

**Comment by DanielRyanSmith** [comment]
This PR should now be refactored and ready for review 🙂

**Review by jrobbins — APPROVED** [review]
I like how much simpler this is with the generic function.

**Pull request merged**
