### PR TITLE
Add api_spec field.

### PR DESCRIPTION
**Pull request by jrobbins**
This helps resolve issue #934.

We had various checkmarks that mentioned an "API overview".  Looking at https://www.chromium.org/blink/launching-features, I think that that refers to a Web IDL spec.

Also in this CL:
+ Simple progress detector function for spec_link
+ Added TODOs for remaining checkmark items that need progress detector functions and/or underlying fields.

### CODE REVIEW

**Comment by jrobbins** [comment]
Screenshots:
+ New feature incubation: https://screenshot.googleplex.com/3PNDQE3WRyoCgAX
+ Existing feature implementation: https://screenshot.googleplex.com/SAZQQP6mh7dEWGm

**Comment by jrobbins** [comment]
Screenshot of intent email:
https://screenshot.googleplex.com/59dDsH9H8mT9ooS

**Review by cwilso — APPROVED** [review]
LGTM!

**Comment by jpmedley** [comment]
An API overview does not refer to the Web IDL spec. It refers to a first crack at a page that can become something like this: https://developer.mozilla.org/en-US/docs/Web/API/AbsoluteOrientationSensor

**Comment by jstenback** [comment]
Hold on, this makes things pretty confusing to developers IMO. What is the actual distinction we're trying to tease out here?

**Comment by cwilso** [comment]
Joe, if you want this to point to something other than the IDL, I think we
should just have the one spec pointer and then we'll need manual review (as
I originally said)

**Comment by jpmedley** [comment]
Maybe I misspoke. I *thought* 'API overview' was the first crack at documentation. I remember lots of discussions about draft documentation using the words 'API overview'. I don't remember any discussions about links to IDL.

**Comment by jrobbins** [comment]
I tried to rebase this PR and I guess I did it wrong.  I will delete this one and send a new one.  The plan discussed last week was to use a checkbox instead of a URL.

**Pull request closed without merging**
