### PR TITLE
Updated hardcoded list of crbug components.

### PR DESCRIPTION
**Pull request by jrobbins**
This should resolve issue #1461, issue #496, and issue #565.

In this PR:
+ Update the hard-coded list of blink components based on info that I got from a monorail API call.
+ Eliminate wf_components because they were not used anywhere.
+ A few whitespace changes crept in

### CODE REVIEW

**Comment by jrobbins** [comment]
The diff of hack_components.py is hard to view on GitHub because it looks like every line changed even though it did not.  I think the problem may have been a conversion of tabs to spaces.   You can view a better diff by using the gear menu just above the diffs and choosing to ignore whitespace.

**Comment by jpmedley** [comment]
@jrobbins If the source of this information in code search were listed in a file comment, it would be easy for anyone on the team to open a PR to update this.

**Review by jpchase — APPROVED** [review]
LGTM.

**Comment by jpchase** [comment]
> @jrobbins If the source of this information in code search were listed in a file comment, it would be easy for anyone on the team to open a PR to update this.

As I understand, the source of this data is an API call to monorail. That is, not easily found in code search.  Unless the API call is easy for anyone to do, perhaps it best to leave out the comment.

**Comment by jrobbins** [comment]
This time was still a manual hack.  I literally viewed the monorail API response for the "project config" in chrome developer tools and then edited it down to just the list of the names of components.  And, I made decisions about which top-level components to include or exclude.  It's not a process that we should repeat.  I'll track a new issue to implement a new automated way to do it, which will involve getting allow-listed for the monorail API.  Eric's old node.js server seems to be completely down at this point, always returning status 410 (Gone).

**Pull request merged**
