### PR TITLE
Add show all button to metrics page

### PR DESCRIPTION
**Pull request by KyleJu**
Add a Show All button - only show the first 30 entries unless user clicks on `Show All`.  This change shouldn't affect the search field.

### CODE REVIEW

**Comment by KyleJu** [comment]
@jrobbins does polymer3 still work in Lit? I am using `iron-collapse` because we include it as a dependency in https://github.com/GoogleChrome/chromium-dashboard/blob/56129b4eab24c7217bf996a54a08dfded11ac7cb/package.json#L95, but it is not rendering when I test it locally with fake data

**Comment by jrobbins** [comment]
polymer components should still work.  In fact, chromestatus is using iron-icon.

Is iron-collapse supposed to render anything when closed?  I thought that you need to implement your own "More" button that sets an attribute to make it show its contents.

**Comment by KyleJu** [comment]
Screen Shot 2022-10-13 at 10 06 19 AM

**Review by jrobbins — APPROVED** [review]

**Comment by KyleJu** [comment]
Tested on staging - https://b1464fc-dot-cr-status-staging.appspot.com/roadmap

**Pull request merged**
