### PR TITLE
Enable http2 push!

### PR DESCRIPTION
**Pull request by ebidel**
R: @jeffposnick @beaufortfrancois

### CODE REVIEW

**Comment by jeffposnick** [comment]
:fire:!

I'll give this a closer look tomorrow. Quick question: what's the process for generating `push_manifest.json`? I don't see any changes to the site's build scripts in this PR.

**Comment by ebidel** [comment]
Because of the server-side templates pages + partials, the npm script I created (https://www.npmjs.com/package/http2-push-manifest) doesn't work very well for discovering resources. For, I'm just maintaining the critical resources on the landing page (/features).

**Comment by jeffposnick** [comment]
Seems to work for me when testing locally. Here are the response headers I'm seeing:

```
link:<http://localhost:8080/static/elements/features-imports.vulcanize.html>; rel="preload"
link:<http://localhost:8080/static/css/main.css>; rel="preload"
link:<http://localhost:8080/static/bower_components/webcomponentsjs/webcomponents-lite.min.js>; rel="preload"
link:<http://localhost:8080/static/elements/features-imports.vulcanize.js>; rel="preload"
link:<http://localhost:8080/features.json>; rel="preload"
link:<http://localhost:8080/static/css/features/features.css>; rel="preload"
link:<http://localhost:8080/omaha_data>; rel="preload"
```

The only question I have is whether the [`as`](https://w3c.github.io/preload/#widl-HTMLLinkElement-as) attribute should be set for those `link` headers. I don't know enough about HTTP/2 to know what the drawback to leaving `as` empty is.

We could also merge as-is now and move that discussion over to https://github.com/GoogleChrome/http2push-gae/issues if you'd like.

**Comment by ebidel** [comment]
AFAIK, `as` isn't supported yet. Moved the convo to: https://github.com/GoogleChrome/http2push-gae/issues/12

Note, there's currently a bug with GAE that does not do server push for custom domains on appspot :\ Ping me if you're interested in tracking that.

**Pull request merged**
