### PR TITLE
Update CSS UMA

### PR DESCRIPTION
**Pull request by ebidel**
R: @beaufortfrancois

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
Would love to LGTM!
One nit, where did you get these new UMAs?

**Comment by ebidel** [comment]
The two links to the source are in uma.py. https://github.com/GoogleChrome/chromium-dashboard/blob/master/uma.py#L3

**Comment by beaufortfrancois** [comment]
LGTM ;)

Do you keep track of it manually or do you have a cron job that alerts you when this file is updated?

**Comment by ebidel** [comment]
Manually for now. See https://github.com/GoogleChrome/chromium-dashboard/issues/97

**Pull request merged**
